# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
		
																																															  
#ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "60"
#ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "8"

default_platform(:ios)

platform :ios do
  desc "Build & test on iOS Simulator (CI-safe, no signing)"
  lane :ci do
    scan(
      project: "TCA_POC.xcodeproj",
      scheme: "TCA_POC",
      device: "iPhone 15",
      clean: true,
      skip_build: false,
      build_for_testing: true
    )
  end
end

